# Daniel Chabeda 12.14.25
#

# This directory contains the necessary files to run a
# solver for the Bethe-Salpether equation in the Tamm-Dancoff
# approximation with static screening. It will take a basis
# of electron and hole quasiparticle states (generated by
# Filter Diagonalization) and compute correlated excitons
# as a linear combination of electron-hole product states.

# Thus, the major convergence parameter is the size of the
# electron/hole basis. The number of electrons and holes is
# set in ./bse/input.par, and is currently 8e/8h. Typical
# calculations for lead halide perovskites require ~100 electrons
# and holes to converge exciton energies and optical properties.

# To run the code, navigate to the ./bse directory and
# 1) link the output.dat file from the filter job
# ln -s PATH_TO_FILTER/filter/output.dat .
# 2) Link the bse_cplx.x executable
# ln -s PATH_TO_EXEC/bse_cplx.x .

# and then run the code with the command
# srun -n 1 ./bse_cplx.x | tee -a run.dat

# The entire code uses an MPI/OpenMP parallelization framework.
# Additional OpenMP threads accelerate calculation of optical
# matrix elements, Fast Fourier Transforms,and two-electron integrals.
# The bottleneck of the code is the calculation of two-electron
# Coulomb integrals (N^4 scaling). MPI implementation splits the
# calculation of integrals onto different nodes. Using more nodes
# is the best way to scale a calculation with many basis states.
# For calculations with few basis states (less than 64 e- or h+ states)
# a single node can still be efficient. For large NCs with huge grids,
# using many threads to parallelize the FFT accelerates the computation.

An example for parallelizing a large job (160e/160h) would be to use
8 nodes, each with 2 MPI ranks for a total of 16 MPI ranks. On a 256 CPU
machine, this leaves 128 CPUs-per-rank -> 64 OpenMP threads on a dual-core machine.
You would set nThreads = 64 in bse/input.par and run
srun -n 16 -c 128 --cpu-bind=cores ./bse_cplx.x
or
mpirun -n 16 -c 128 --cpu-bind=cores ./bse_cplx.x


# ============================================================================
# RUNNING ON GPU (Perlmutter A100)
# ============================================================================
# bse_cplx can offload the Coulomb kernel (the N^4 bottleneck) to a GPU while
# keeping native double-complex results identical to the CPU path. See
# ../../BSE_CPLX_GPU.md for the full write-up. Quick start:
#
# 1) Build the GPU executable (NVHPC + cray-libsci toolchain). From bse_cplx/:
#      source LOAD_COMPILE_ENV_NVHPC.sh      # sets PrgEnv-nvidia + cray-fftw/libsci
#      make clean && make                    # -> bse_cplx_gpu.x
#    (`make clean` matters: the GPU and Intel/MKL builds share .o names. The
#     original CPU build is still available via `make -f Makefile_mkl`.)
#
# 2) In ./bse, link the inputs and the GPU executable:
#      ln -s PATH_TO_FILTER/filter/output.dat .
#      ln -s /global/common/software/m4868/FilterBSE/bse_cplx/bse_cplx_gpu.x .
#
# 3) The GPU is requested by `gpuAccel = 1` in input.par (already set here) and
#    is auto-gated by device availability -- on a CPU-only node it silently runs
#    the host path. Submit the batch script (edit -A account / paths as needed):
#      sbatch submit_bse_gpu.sh
#    or, in an interactive GPU allocation:
#      source /global/common/software/m4868/FilterBSE/bse_cplx/LOAD_COMPILE_ENV_NVHPC.sh
#      export BSE_GPU_MEM_GB=36
#      srun -n 1 ./bse_cplx_gpu.x | tee run.dat
#    The log prints which path ran, e.g.
#      "Coulomb kernel: GPU offload ENABLED (1 device(s) visible)"
#
# 4) Verify correctness -- the GPU result must match the CPU path exactly.
#    Run the SAME binary twice and diff the eigenvalues:
#      OMP_TARGET_OFFLOAD=DISABLED srun -n 1 ./bse_cplx_gpu.x > run_cpu.dat   # host
#      mv BSEeval.par BSEeval_cpu.par
#      srun -n 1 ./bse_cplx_gpu.x > run_gpu.dat                              # device
#      diff BSEeval_cpu.par BSEeval.par        # -> no output = identical
#
# NOTE: 1x1x1 is a tiny validation case; the GPU offload only *wins* at
# production grid/basis sizes (large NCs, ~100+ e-/h+). Here it checks
# correctness, not speed.
