#include "fd.h"
#include "aux.h"
#include "energy.h"
#include "Hmat.h"

void mod_diag(
    double *psitot,
    double *pot_local,
    double *eig_vals,
    double *sigma_E,
    vector *G_vecs,
    vector *k_vecs,
    grid_st *grid,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double *ksqr,
    zomplex *an,
    double *zn,
    double *ene_targets,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);
