#include "fd.h"
#include "hamiltonian.h"
#include "energy.h"
#include "coeff.h"
#include "aux.h"

void run_filter_cycles(
    double *psi_rank,
    double *pot_local,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double *ksqr,
    zomplex *an,
    double *zn,
    double *ene_targets,
    grid_st *grid,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);

void filter_cycle(
    double *psi_rank,
    long jns,
    zomplex *psi,
    zomplex *phi,
    double *pot_local,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double *ksqr,
    zomplex *an,
    double *zn,
    double *ene_targets,
    grid_st *grid,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel,
    fftw_plan_loc planfw,
    fftw_plan_loc planbw,
    fftw_complex *fftwpsi);

void p_hnorm(
    zomplex *psi_out,
    zomplex *psi_tmp,
    double *pot_local,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double *ksqr,
    double zn,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel,
    fftw_plan_loc planfw,
    fftw_plan_loc planbw,
    fftw_complex *fftwpsi);

void time_hamiltonian(
    zomplex *phi,
    zomplex *psi,
    double *pot_local,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double *ksqr,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);

void gather_mpi_filt(
    double *psi_rank,
    double **psitot,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);

// Periodic: gather one k-point's filtered states from the ranks of a k-group
// (communicator comm) into the master's psitot slot. prs = per-rank element count
// for this k = n_states_per_rank * stlen. psitot_kslot must be preallocated on the
// root with room for comm_size * prs doubles; ignored on non-root ranks.
void gather_mpi_filt_k(
    double *psi_rank_kblock,
    double *psitot_kslot,
    long prs,
    long stlen,
    long n_states_per_rank,
    MPI_Comm comm,
    int root);

void send_recv_lg_data(
    double *psi_rank,
    double **psitot,
    long stlen,
    long n_states_per_rank,
    int mpi_rank,
    int mpi_size,
    MPI_Comm comm,
    int root);

/*************************************************************/

void run_filter_cycles_k(
    double *psi_rank,
    double *pot_local,
    grid_st *grid,
    vector *G_vecs,
    vector *k_vecs,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    zomplex *an,
    double *zn,
    double *ene_targets,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);

void filter_cycle_k(
    double *psi_rank,
    long jns,
    int ik_global,
    zomplex *psi,
    zomplex *phi,
    double *pot_local,
    vector *G_vecs,
    vector k,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    zomplex *an,
    double *zn,
    double *ene_targets,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel,
    fftw_plan_loc planfw,
    fftw_plan_loc planbw,
    fftw_complex *fftwpsi);

void p_hnorm_k(
    zomplex *psi_out,
    zomplex *psi_tmp,
    double *pot_local,
    vector *G_vecs,
    vector k,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    double zn,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel,
    fftw_plan_loc planfw,
    fftw_plan_loc planbw,
    fftw_complex *fftwpsi);

void time_hamiltonian_k(
    zomplex *psi_out,
    zomplex *psi_tmp,
    double *pot_local,
    vector *G_vecs,
    vector k,
    grid_st *grid,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);
