#include "fd.h"
#include "init.h"
#include "energy.h"
#include "hamiltonian.h"
#include "filter.h"
#include "coeff.h"

void mod_filter(
    double *psi_rank,
    zomplex *psi,
    zomplex *phi,
    double *pot_local,
    grid_st *grid,
    zomplex *LS,
    nlc_st *nlc,
    long *nl,
    zomplex *an,
    double *zn,
    double *ene_targets,
    double *ksqr,
    lattice_st *lattice,
    vector *G_vecs,
    vector *k_vecs,
    index_st *ist,
    par_st *par,
    flag_st *flag,
    parallel_st *parallel);
